# Generated by Django 4.0.3 on 2023-03-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalepersonHistory',
        ),
    ]
