# Generated by Django 4.0.3 on 2023-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappoitment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceappoitment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
